-- V1: esquema inicial de Krypton E-commerce (8 tablas)

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    email      VARCHAR(160) NOT NULL UNIQUE,
    password   VARCHAR(120) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(60)   NOT NULL UNIQUE,
    name        VARCHAR(150)  NOT NULL,
    description VARCHAR(2000),
    price       NUMERIC(12,2) NOT NULL,
    stock       INTEGER       NOT NULL DEFAULT 0,
    image_url   VARCHAR(500),
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    category_id BIGINT        NOT NULL REFERENCES categories (id)
);

CREATE TABLE cart (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL UNIQUE REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE cart_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT  NOT NULL REFERENCES cart (id),
    product_id BIGINT  NOT NULL REFERENCES products (id),
    quantity   INTEGER NOT NULL
);

CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NOT NULL REFERENCES users (id),
    order_date TIMESTAMPTZ   NOT NULL DEFAULT now(),
    status     VARCHAR(20)   NOT NULL,
    total      NUMERIC(12,2) NOT NULL
);

CREATE TABLE order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT        NOT NULL REFERENCES orders (id),
    product_id BIGINT        NOT NULL REFERENCES products (id),
    quantity   INTEGER       NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL          -- snapshot del precio al comprar
);

CREATE TABLE stock_movement (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES products (id),
    type       VARCHAR(20) NOT NULL,           -- ENTRADA | SALIDA
    quantity   INTEGER     NOT NULL,
    reason     VARCHAR(120),
    reference  VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT      REFERENCES users (id)
);

CREATE INDEX idx_products_category     ON products (category_id);
CREATE INDEX idx_cart_item_cart        ON cart_item (cart_id);
CREATE INDEX idx_order_items_order     ON order_items (order_id);
CREATE INDEX idx_stock_movement_product ON stock_movement (product_id);
