-- V5: tabla product_image — soporte multi-imagen con carrusel por producto

CREATE TABLE product_image (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT       NOT NULL REFERENCES products (id),
    path          VARCHAR(500) NOT NULL,
    display_order SMALLINT     NOT NULL DEFAULT 0,
    is_cover      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Índice general para listados por producto
CREATE INDEX idx_product_image_product
    ON product_image (product_id);

-- Índice único parcial: solo puede haber UNA imagen portada por producto
CREATE UNIQUE INDEX idx_product_image_cover
    ON product_image (product_id)
    WHERE is_cover = TRUE;
